const iconPackConverter = [
  {
    apps: ["com.android.dialer", "com.samsung.android.incallui","com.samsung.android.dialer"],
    icon: "",
    pack: 0,
  },
  {
    apps: [
      "com.google.android.apps.messaging",
      "com.android.apps.messaging",
      "com.samsung.android.messaging",
    ],
    icon: "",
    pack: 0,
  },
  { apps: ["com.android.settings"], icon: "", pack: 1 },
  { apps: ["com.discord","com.aliucord"], icon: "", pack: 0 },
  { apps: ["com.android.chrome"], icon: "", pack: 1 },
  { apps: ["com.spotify.music"], icon: "", pack: 1 },
  { apps: ["com.reddit.frontpage"], icon: "", pack: 1 },
  { apps: ["com.google.android.googlequicksearchbox"], icon: "", pack: 1 },
  { apps: ["com.valvesoftware.android.steam.community"], icon: "", pack: 1 },
  { apps: ["com.pinterest"], icon: "", pack: 1 },
  { apps: ["com.linkedin.android"], icon: "", pack: 1 },
  { apps: ["com.facebook.katana"], icon: "", pack: 1 },
  { apps: ["com.facebook.orca"], icon: "", pack: 1 },
  { apps: ["com.chess"], icon: "󰡙", pack: 1 },
  { apps: ["org.lichess.mobileapp"], icon: "", pack: 1 },
  { apps: ["com.ebay.mobile"], icon: "", pack: 1 },
  { apps: ["org.mozilla.firefox"], icon: "󰈹", pack: 1 },
  { apps: ["com.google.android.apps.fitness"], icon: "󰥬", pack: 1 },
  { apps: ["com.instagram.android"], icon: "", pack: 1 },
  { apps: ["org.krita"], icon: "", pack: 1 },
  { apps: ["com.netflix.mediaclient"], icon: "󰝆", pack: 1 },
  { apps: ["app.revanced.android.youtube","com.google.android.youtube"], icon: "", pack: 1 },
  { apps: ["com.google.android.apps.youtube.creator"], icon: "󰡇", pack: 1 },
  { apps: ["com.google.android.apps.maps"], icon: "", pack: 1 },
  { apps: ["com.whatsapp"], icon: "", pack: 1 },
  { apps: ["com.sec.android.app.voicenote"], icon: "󰍬", pack: 1 },
  { apps: ["org.telegram.messenger"], icon: "", pack: 1 },
  { apps: ["org.torproject.torbrowser"], icon: "", pack: 1 },
  { apps: ["com.google.android.apps.translate"], icon: "󰗊", pack: 1 },
  { apps: ["com.samsung.android.app.tips"], icon: "󰌵", pack: 1 },
  { apps: ["com.samsung.android.game.gamehome","com.google.android.play.games"], icon: "󰖺", pack: 1 },
  { apps: ["com.microsoft.teams"], icon: "󰊻", pack: 1 },
  { apps: ["com.skype.raider"], icon: "", pack: 1 },
  { apps: ["com.snapchat.android"], icon: "", pack: 1 },
  { apps: ["com.microsoft.skydrive"], icon: "", pack: 1 },
  { apps: ["com.microsoft.office.onenote"], icon: "󰝇", pack: 1 },
  { apps: ["com.microsoft.office.outlook"], icon: "󰴢", pack: 1 },
  { apps: ["com.microsoft.office.officehubrow"], icon: "󰏆", pack: 1 },
  { apps: ["com.google.android.gm","com.samsung.android.email.provider"], icon: "󰏆", pack: 1 },
  { apps: ["com.google.android.gm","com.samsung.android.email.provider"], icon: "󰏆", pack: 1 },
  { apps: ["com.android.vending"], icon: "", pack: 1 },

  { apps: ["com.sec.android.app.popupcalculator"], icon: "󰃬", pack: 1 },
  { apps: ["com.sec.android.app.camera"], icon: "󰄀", pack: 1 },
  { apps: ["com.samsung.android.calendar"], icon: "󰸗", pack: 1 },
  { apps: ["com.android.stk"], icon: "󰒧", pack: 1 },
  { apps: ["com.sec.android.app.music"], icon: "", pack: 1 },
  { apps: ["com.google.android.apps.docs"], icon: "", pack: 1 },
  
];
export default iconPackConverter;
